### ISSUE TITLE
Add option for full axis lock-down when scrolling

### ISSUE THREAD

**Issue by fastaddons** [fastaddons/ScrollAnywhere#10]
Right now we partially lock X / Y axis only when container is scrollable in one axis but one of the parent containers is scrollable in another axis.
The partial lock is like a momentum which allows you to change direction during scrolling.

The new option should be lock scrolling axis the moment first XX scroll events fires.

However, just like the partial lock, this may be better to activate only when container is scrollable in one axis (with parent scrollable in other axis), otherwise some containers that should be easy to scroll in both axes (like a zoomed picture), will not be so scrollable anymore.

**Comment by halejok** [comment]
Thanks for your answer regarding the issue I described to you (https://addons.mozilla.org/de/firefox/addon/scroll_anywhere/reviews/1539296/):
It occurs when the text selection by horizontal mouse movement starting from outside texts. To start a selection, it's necessary that the cursor must very precisely position over a character or at the beginning or end of a word. The smaller the font size, the more difficult it's to select the text.

Selecting text it's more convenient by moving the cursor in a line or slight arc-shaped starting from outside the text. That is a more natural way or behavior to select (see the screen capture).

The scrolling should be locked when the cursor starts to move horizontally.

Regards, hjok

![scrollanywhere 01](https://user-images.githubusercontent.com/50183502/82710424-209c8980-9c83-11ea-8ced-08ee781a0d09.gif)

**Comment by fastaddons** [comment]
I've added new section Axis locking in the Options page where you can define how will axis be locked if page is scrollable in both directions.

It will part of the 8.4 release, any day now (I just need to test all new features and make a release).

@halejok the problem with selecting text is not possible to fix by detecting direction - because to detect direction you need at least 2 events (to know where are you moving), but the decision if you will scroll or select text must be done when first event fires.

**However there is one good workaround** - instead of trying to click to the beginning of the word, use simple double click on the first word and then while holding your mouse button continue selecting text - this will select whole first word and everything else as you drag down.
