### ISSUE TITLE
Yesterday's update (2020-04-10) broke thin bars probably on firefox.

### ISSUE THREAD

**Issue by wtfzambo** [fastaddons/ScrollAnywhere#12]
**Describe the bug**
Thin bars not thin anymore in Firefox v. 75.0

**Steps To Reproduce**
1. Have thin bars enabled in Firefox v. 75 (latest version).
2. Go to any website that has a scrollbar, like [youtube](www.youtube.com).
3. The problem is that 'scrollbars aren't thin any more'.

**Expected behavior**
Scrollbars are actually thin when enabled.

**Device info:**
 - OS: Windows 10 Home, version 1903 build 18362.720 
 - Browser: Firefox 75.0
 - ScrollAnywhere version: 8.3

**Comment by Juraj-Masiar** [comment]
Try to restart your Firefox.
There was a new update released so existing opened pages may get broken...
If it persists after restarting, could you send me your settings? From the Options page / Backup / Export. You can send it to my support email admin[a}fastaddons.com

**Comment by wtfzambo** [comment]
Did restart firefox indeed, multiple times, but to no avail. I'll send you the settings.

**Comment by fastaddons** [comment]
So the problem is that you have disabled the addon - there is On/Off switch in the toolbar icon menu.
The recent update added this - when addon is disabled, all of it's features are disabled (including scrollbars change).

If you don't want to use the scrolling ability of my addon only the scrollbar change, you can switch the "Disable / Enable scrolling when key is down:" option to "Enable when key is down" and not specify any key (see the General tab).

**Comment by wtfzambo** [comment]
Oh, ok! I was unaware of that. I had it enabled in firefox extensions and I had totally forgotten that there was a switch in the toolbar icon! I'm sorry for wasting your time with something so trivial.

**Comment by fastaddons** [comment]
no problem :)

**Comment by fastaddons** [comment]
Actually the fact that you didn't know that the addon is disabled points to a bad user interface design.
Even I had problem find out what's wrong after importing your data.... so this needs fixing.
Thank you for reporting! I'm gonna file a new bug for this :)

**Comment by wtfzambo** [comment]
Ehh, I probably disabled it manually, iirc, when I installed it, because I was only looking for the thin bar functionality and didn't need the scrolling behavior. Then I obviously removed this info from my brain and totally forgot about it.

I could suggest a couple quick fixes if you wanna address this from a UX/UI perspective:

- Make the icon more visible in the toolbar, either by redesigning it or changing the color. I have many icons and that one is relatively small in comparison. With dark mode also the contrast is not enough. Pic for reference:

![image](https://user-images.githubusercontent.com/47462792/79050754-6568e580-7c2c-11ea-9cd8-b91c0d929808.png)

- More importantly: make the icon have 2 states, for disabled and enabled. For example, I have a "night mode" addon and it does like this:

![image](https://user-images.githubusercontent.com/47462792/79050786-9a753800-7c2c-11ea-94ce-e2c13d7d0ca6.png) Turned off.

![image](https://user-images.githubusercontent.com/47462792/79050788-a234dc80-7c2c-11ea-98b9-0322e1c1fff8.png) Turned on.

**Comment by fastaddons** [comment]
Good points, the two state icon is part of the new issue:
https://github.com/fastaddons/ScrollAnywhere/issues/13

I will try to edit the icon to make it more visible, thanks!
