### ISSUE TITLE
Infinite scrolling

### ISSUE THREAD

**Issue by samwolfe2000** [fastaddons/ScrollAnywhere#14]
Hey,

I thought of a function **to loop the cursor on the screen** when scrolling by always setting the cursor position on the opposite side of the screen when an edge is reached.

Do you think it's possible?

Regards,
Sámuel

**Comment by fastaddons** [comment]
Hello Sámuel,

Sadly no, this is not possible. JavaScript cannot control cursor position.

However there are desktop applications that can do this on operating system level, for example:
https://www.ghacks.net/2020/04/06/customize-the-mouse-pointers-movement-and-behavior-with-winmouse/

This should allow you to continue dragging as long as you have table under your mouse :).

**Comment by samwolfe2000** [comment]
Thanks for the suggestion, unfortunately the 3rd party solution doesn't
work with ScrollAnywhere, the page jumps back every time the cursor gets
teleported.
I will try to live without it :S



Juraj Mäsiar <notifications@github.com> ezt írta (időpont: 2020. ápr. 14.,
Ke 13:02):

**Comment by Juraj-Masiar** [comment]
Hmm, yes that actually makes sense. I'm sorry for a bad advice.

But maybe I can fix it for this case - I could add new option to "Ignore big scroll jumps" which would not jump back when mouse gets teleported across whole screen.
I will check it out when I get to this addon again.

**Comment by samwolfe2000** [comment]
Wow, you are ambitious I have to say :D you really don't believe in edge
cases.

Juraj Mäsiar <notifications@github.com> ezt írta (időpont: 2020. ápr. 25.,
Szo, 8:48):

**Comment by fastaddons** [comment]
New option in Options page / Advanced / "Prevent big jumps" will ignore any scrolling if mouse cursor moves more than 50% of window height/width since last position. I've tested it and it works well with desktop tools to teleport cursor.
**It will be part of the 8.4 release**, probably by the end of this week (there is few more small features I want to include in the release).
