### ISSUE TITLE
Chrome PDF viewer may support scrolling

### ISSUE THREAD

**Issue by fastaddons** [fastaddons/ScrollAnywhere#15]
So it doesn't work right now, but I can see other extensions are being loaded in PDF tabs, so it must be possible.
I will investigate and if possible, I will fix it in the next release 8.4

**Comment by fastaddons** [comment]
So after further investigation and testing this seems to be impossible.
It seems that my content script is injected and running, but no DOM event handlers are executed and I can't set scroll position or anything.
Testing PDF page:
http://www.africau.edu/images/default/sample.pdf

**Comment by pfugwtg** [comment]
It's so sad😭
