### ISSUE TITLE
Issues with scrolling point restoring

### ISSUE THREAD

**Issue by samwolfe2000** [fastaddons/ScrollAnywhere#18]
Hey,

The update is awesome, I was looking forward to it. 

I've been testing the features for a while, and I noticed some issues with the scrolling point restoring script.

**1.** Jumping back to the original scrolling point (when you leave the scrolling area) works well, but **jumping "forward"** to the new one (when you enter the scrolling area) **works unreliably**. I couldn't figure out any rule: sometimes it jumps, sometimes it doesn't.

Smaller issues:

**2.** if the script is used **with infinite scrolling, jumping "forward" doesn't restore the new position**, only moves the old position the amount the cursor is away from the initial cursor postition. This is not a crucial problem, but probably requires to rewrite a handful amount of the script, see if the fix actually worth the affort or not.

**3.** **when escape is used** to revert position and m2 is used for scrolling, **context menu appeares** at release.

These are the issues I found. 

Thanks for your conscientious work.

Sam

**Comment by fastaddons** [comment]
Hello,
Thanks for reporting!
The scrolling area doesn't work well with "iframes", especially in Chrome. I forgot to fix it before releasing. But I'm not sure if that's what you are referring to.
The behavior should be simple, from the point where scrolling starts you can move up-to XX pixels, then it reverts back, returning back continues scrolling. It should be the same as when using scrollbar.

Regarding 2. point :D, man that's interesting use case (edge case). Yeah, I don't think I will be able to fix this, I have no idea how.

Regarding 3, that's should be easy fix.
Thanks again for reporting these!

**Comment by samwolfe2000** [comment]
Sorry, I forgot to mention the platform I was testing on, it was Firefox.

Now I've tested the chrome version as well, which has no unreliability issues.

**Comment by fastaddons** [comment]
New version 8.6 is now available and it fixes the 3rd issue with ESC key and context menu.
