### ISSUE TITLE
Enabling left+right buttons prevents context menu for copy & paste

### ISSUE THREAD

**Issue by BlueMax** [fastaddons/ScrollAnywhere#22]
Hallo,
when left+right buttons for 'grab & drag' is enabled its not possible to get into the copy & paste context menu when text is marked. The firefox generic context menu appears instead. Sometimes the correct context menu appears though.

**Steps To Reproduce**
1. Click once to enable text mode.
2. Mark text.
3. Press right mouse button to open context menu.
4. Wrong context menu appears.

This only happens when both buttons (left+right) are enabled. 
I've tried several other option combinations (lock iframes, etc) but nothing helped.

**Device info:**
 - Arch Linux 5.8.10
 - Firefox 80.0.1
 - ScrollAnywhere 8.4

**Comment by BlueMax** [comment]
The 'wrong context menu' is the one that appears when you (normally) do not have text marked (with page back/forward arrows, add to favorites (star), etc at the top. There are no 'copy, cut, paste' entries. The marked text seems to get unmarked beforehand. Maybe its a race condition or timing problem.

**Comment by Juraj-Masiar** [comment]
Thanks @BlueMax for the clarification, I will check it out before the next release.
Currently I'm working on my speed dial addon so the next release here may take a while... I'm quite busy with so many projects so things are moving slowly.

**Comment by fastaddons** [comment]
New version 8.6 is now available and it fixes the bad context menu (caused by deselected text on mouse down).
I'm really sorry it took me this long to fix this.
