### ISSUE TITLE
spreadsheets Dont work 

### ISSUE THREAD

**Issue by Milor123** [fastaddons/ScrollAnywhere#24]
**Describe the bug**
Try alternate all settings in the extension for enable scroll whie edit a spreadsheets in "docs.google.com"

**Steps To Reproduce**
1. Go to spreadsheets  in docs.google.com
2. Try with all
3. Nothing scroll works

**Expected behavior**

**Device info:**
 - Windows 10 64bits
 - Firefox 81.0.1 (64-bit)
 - ScrollAnywhere version: 8.4

**Comment by fastaddons** [comment]
Thank you for reporting. I will check it out before the next release.
I'm currently quite busy with my other addons so this may take a while...

**Comment by Paul-Huntsberry** [comment]
This is also a problem with Microsoft Excel spreadsheets in a browser (OneDrive / Office365) using Chrome.

**Comment by fastaddons** [comment]
So this was much much harder than I thought. It took me 3 whole days to make this work in Google Shits!
Crazy hard, also I'm not 100% happy with the result, but we will see. I will try to release it soon.

Now regarding the Microsoft office if I understand this is a payed product that I can't just visit and test? Right?
It feels like an enterprise feature, I'm not sure I feel like doing that one for free. Especially if I'm gonna spend another 3 days with it :(. It's not like I'm getting payed here :(

**Comment by Paul-Huntsberry** [comment]
Thanks for all your hard work.

For Microsoft Excel, here is a test public file online:
https://bit.ly/3gxrES4

Right now, the scrollbar still disappears even it the extension is disabled.

**Comment by fastaddons** [comment]
Thank you for the file Paul!

So the scrolling works there, right?
So the problem is that you have enabled option to hide all scrollbars but you want to see them in the Microsoft Excel? And you checked the "Disable on ... domain" but it's still disabled?
If not, please describe :). Thanks!

**Comment by Paul-Huntsberry** [comment]
That is correct. Even though the checkmarks are checked to disable on the site, it still does not show the scrollbars.  When trying to select cells it scrolls vertically and horizontally. 

On a side note, if you click on the actual blue checkbox, it doesn't toggle the checkbox, you have to click on the text to Disable.

![image](https://user-images.githubusercontent.com/17347127/101673543-2afa5700-3a0c-11eb-8c51-6ab828450d59.png)

**Comment by Juraj-Masiar** [comment]
Thanks Paul! 
I will check this out in the morning and try to fix it in the upcoming version.

**Comment by fastaddons** [comment]
New version 8.6 is now available and it adds Google Sheets scrolling and it correctly applies scrollbar style only on pages where scrolling is enabled.
