### ISSUE TITLE
Grab and drag scrolling for touchscreens without requiring any keys to be pressed concurrently

### ISSUE THREAD

**Issue by mYnDstrEAm** [fastaddons/ScrollAnywhere#29]
**Is your feature request related to a problem? Please describe.**
Since the "Grab & Drag" addon isn't anymore, this addon seems to be the only way to get touchscreen scrolling to work in Firefox with GNU/Linux - thanks for developing this!
When enabling "grab and drag" scrolling in the options one still has to press a keyboard button or a mouse button to enable the scrolling. This is not as convenient as when only having to drag on the screen - for example when reading news or ebooks/PDFs with a laptop. Furthermore it doesn't work with devices like convertibles for which you can't easily press any keyboard button once you convert it to a tablet. It may also not work with smartphones like the Librem 5 (btw maybe this addon could be preinstalled or recommended for that phone.)

**Describe the solution you'd like**
I'd like to ask for an option to scroll via grabbing & dragging only without having to press any key or mouse button. This already works in the settings window where you can test the scrolling on the right so it probably only needs to be enabled for the browser if I'm not missing anything here.

I think it would even be good if this option was enabled by default when enabling the "grab and drag" scrolling in the options so you have to choose buttons/keys to be pressed if you'd like that to be required for the scrolling.

**Describe alternatives you've considered**
This is less a suggested alternative than an extension: one could also add a button to the Firefox menu to quickly toggle between scrolling by dragging and scrolling by clicking/keyboard-press + dragging.

**Additional context**
System is Debian10/KDE/Firefox78.6

**Comment by fastaddons** [comment]
Hello,
Did you tried to activate the left button scrolling? That may work on touch devices.
The main problem here is that I don't have any way to test it. 
Also I would expect these convertible devices to have some build in touch-scrolling feature and not requiring an addon from poor developer from Slovakia to do the work for them :).

**Comment by mYnDstrEAm** [comment]
Hi, yes I have "Left button (experimental)" enabled. It doesn't work when pressing the left mouse button and dragging but I found that it does work when changing "Enable when key is down:" to "Disable when key is down:" and ticking e.g. the Ctrl button (at the bottom of the addon's General settings). Amazing - it works now!

Is that a new option or did I just miss it before (or maybe dragging with disabling via key just didn't work before with the firefox/addon version/s)?

Doesn't look like there's a touch-scrolling feature for Debian/KDE built-in yet so this really is the only way to get it working for the browser at least. Thank you!
