### ISSUE TITLE
Add option to make the toolbar icon the main switch for ON / OFF

### ISSUE THREAD

**Issue by fastaddons** [fastaddons/ScrollAnywhere#31]
Sometimes all that user needs is simple on/off feature.
The options available from Pop-up are still accessible from the Options page which can be opened from the about:addons page, so no features will be lost by activating this mode.

**Comment by sphh** [comment]
Thanks for adding my suggestion here (which was sent by email, because I could not find a link to this github repository).

**Comment by fastaddons** [comment]
Done, version 8.7 has now new option "Use toolbar icon as the main ON / OFF switch" in the Options page / General tab / Disable addon section.
It's released in Chrome store and Thunderbird store, Firefox is still pending because of the Recommended status (each update have to be reviewed by human)... currently "Queue Position: 17 of 18".

**Comment by sphh** [comment]
Thanks a lot!!
