### ISSUE TITLE
Values' limits

### ISSUE THREAD

**Issue by irvnriir** [fastaddons/ScrollAnywhere#37]
Please increase the "Smart lock stack size" max value to 500 or ∞ .

**Comment by fastaddons** [comment]
No problem :) I can increase it in the next release, but not infinite - that's what "Strict lock" is for. I've noticed for example Firefox on Android is using strict lock.

**Comment by irvnriir** [comment]
@fastaddons the scroll Multiplier setting too, could use such value increase to 20 X)

**Comment by fastaddons** [comment]
100 is probably waaaay too much. The limits are here to protect users from breaking their scrolling :)

**Comment by irvnriir** [comment]
@fastaddons i mean it for "Grab and Drag" + "Reverse scroll direction" :) , i guess 100 should still work (of cource its a top limit) .
it may allow to "break" some other options, but that shouldn't affect case when it may be needed .

**Comment by irvnriir** [comment]
at least 20 Multiplier would be highly appreciated .

**Comment by fastaddons** [comment]
I'm sorry for the delay, I'm still working on the new release and I need at least a week or more.

**Comment by fastaddons** [comment]
Fixed in 8.8, will be released in a few days.
I'm really sorry for the insane delay... I can't believe it took me almost a year to get to this addon again. Crazy how fast things goes :(, and yet I have still so many other things to do.... there is just no end.
Anyway, have a nice weekend :)
