### ISSUE TITLE
[Firefox] Momentum doesn't work with "Enable when key down" option selected

### ISSUE THREAD

**Issue by alarcondgtuc** [fastaddons/ScrollAnywhere#45]
In firefox when selecting the option to "Enanle when key down" and pressing that key momentum doesn't works.

Happens with all buttons (left, middle right), with Grab and Drag option selected.

**Expected behavior**
I expected that I could use it when I required by pressing Ctrl and drag the page, then continue without draging.

**Device info**
 - Windows 10 64 bits
 - Firefox 93.0

**Additional info**
Enable momentum is ticked
I don't have any "disabled on" pages

**Comment by fastaddons** [comment]
Fixed in upcoming 8.8, will be released in a few days.
I'm sorry for the huge delay, I've build too many addons and now I have to work on all of them :)
