### ISSUE TITLE
context pops up 

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [fastaddons/ScrollAnywhere#54]
Error: When when releasing the mouse button always the context menue pops up.
Addendum: OS Windows 10, Firefox.

**Comment by fastaddons** [comment]
Hello,
Could you open: "about:config" page and check that "dom.event.contextmenu.enabled" is set to true?

Also, was this working before?
And are you using some other addons that could interfere? For example some gestures addon?

**Comment by Clemens-Ratte-Polle** [comment]
YES! Now it does it! Thx! :D 
Before some time it was working correctl but lost somehow.
