### ISSUE TITLE
Could not load manifest

### ISSUE THREAD

**Issue by fenix011** [fastaddons/ScrollAnywhere#55]
**Describe the bug**
While installing it in Chromium

**Steps To Reproduce**
Load the unpacked extension

**Expected behavior**
installation of the extension

**Device info:**
 - operating system: Guix
 - Browser and version: Chromiun 103
 - addon version: latest

**Additional info**

Failed to load extension
File
~/Utils/ScrollAnywhere-master
Error
Manifest file is missing or unreadable
Could not load manifest.

**Comment by fastaddons** [comment]
Hello,
Yeah, that won't work, I have sources in the private bitbucket repo.
As mentioned in the "About" section, "This repository is for tracking bugs and documentation only".
As to why, see: https://github.com/fastaddons/ScrollAnywhere/blob/master/LICENSE

**Comment by fenix011** [comment]
AH... the thing is that the Chromium build i'm using  only allows me load unpacked extensions.
Hence, if i'm not missing something (which i probably do), i cannot install your useful ScrollAnywhere extension ?

​​​​​​Thanks, thanks, thanks !

F
​​​​​
On Monday, October 03, 2022 11:37 CEST, Juraj Mäsiar ***@***.***> wrote:
 
 
Hello,
Yeah, that won't work, I have sources in the private bitbucket repo.
As mentioned in the "About" section, "This repository is for tracking bugs and documentation only".
As to why, see: https://github.com/fastaddons/ScrollAnywhere/blob/master/LICENSE

**Comment by fastaddons** [comment]
Hmmm, I think you should be able to download the extension file and load it as unpacked.
For example, Rob Wu wrote this page that can download chrome extensions:
https://robwu.nl/crxviewer/

Simply enter my extension url there:( "https://chrome.google.com/webstore/detail/scrollanywhere/jehmdpemhgfgjblpkilmeoafmkhbckhi?hl=en") and then click "Download" in the upper right corner.
That should give you extension file.
There may be other ways to download extensions from store...

**Comment by fenix011** [comment]
Got it working . 
Thanks, thanks, thanks
