### ISSUE TITLE
Context pops up

### ISSUE THREAD

**Issue by erikschul** [fastaddons/ScrollAnywhere#61]
**Describe the bug**
When using right-click to scroll, the context menu appears 80% of the time, 20% of the time the scroll works as expected.

**Steps To Reproduce**
Enable right-mouse scrolling.
On a page with text (e.g. GitHub), right-down and move the mouse. Context menu shows.

**Expected behavior**
Previously worked correctly.

**Device info:**
 - operating system: MacOS Ventura 13.3.1
 - Browser and version: Firefox 112.0
 - addon version: 9.2

**Additional info**

**Comment by Juraj-Masiar** [comment]
Was it working fine before?
Also, does it work in the "testing area" in the Options page? Or is it broken only on some specific pages.

**Comment by erikschul** [comment]
Yes it was working fine a few months ago. I haven't noticed exactly when it stopped working, because I mostly use touchpad, only my mouse sometimes.

The problem also occurs in the "testing area":
<img width="402" alt="image" src="https://user-images.githubusercontent.com/128804597/232023823-37fb4a12-3635-45c7-a472-34518d3c07bc.png">

**Comment by Juraj-Masiar** [comment]
Is the context menu displayed when you press or when you release the right button?
Also, if it was working before, then try to uninstall it, restart Firefox (make sure Firefox is not running, you may need to right click the Firefox icon and select "quit"). Then install it back.

**Comment by erikschul** [comment]
Context menu shows on mouse down.
If I mousedown, mouseup, mousedown, the context menu disappears, and I am able to scroll until mouseup.
So the problem seems to be that ScrollAnywhere does not have priority over context menu on right click.

**Comment by erikschul** [comment]
Uninstalling the extension, quitting firefox, and reinstalling the extension, did not solve the problem.

**Comment by Juraj-Masiar** [comment]
When you enabled "Right button" scrolling, it should ask you if you want to change system setting - to show context menu on mouse up, not mouse down event.
Try to disable / enable right button scrolling checkbox now.

If it's not asking you that, try this:
1. open "about:config" page
2. use filter to find "ui.context_menus.after_mouseup" and make sure it's set to "true"

**Comment by erikschul** [comment]
Ah, sorry. It works now.

I see the guide text now. I used Windows before, so I've read the text before, but it didn't apply to me, and then next time, I didn't read it, out of habit. Silly!

```
Linux / Mac users - you will be prompted for new permission "Read and modify browser setting" - this is required to suppress context menu being shown before scrolling!
```
