### ISSUE TITLE
"Disabled on pages / sub-pages" not working

### ISSUE THREAD

**Issue by xianghongai** [fastaddons/ScrollAnywhere#63]
**Describe the bug**

"Disabled on pages / sub-pages" not working.

**Steps To Reproduce**

When I set `mastergo.com/file/*` in `Disabled on pages / sub-pages`, execute `Save Changes`, return to "https://mastergo.com/file/<id>" the page and refresh can be disabled as expected.

but, when I close and restart the browser, the disabled configuration becomes invalid.

**Expected behavior**

I hope that the disabled configuration will always take effect.

**Device info:**

 - operating system: Ubuntu 22.10
 - Browser and version: Version 113.0.5672.126 (Official Build) (64-bit)
 - addon version: 9.1

**Comment by Juraj-Masiar** [comment]
Hello,
Are you saying that after the restart this input is empty?
![image](https://github.com/fastaddons/ScrollAnywhere/assets/6358971/cc780fde-a22b-47bf-837e-7edf552e1dce)

Try to change some other settings to see if they are reset too.
Because it sounds like something is deleting the settings.
What browser are you using? You wrote version but not name  :), I would guess it's Chrome?

**Comment by xianghongai** [comment]
`Disabled on pages / sub-pages` There is configuration data in the input box, but it is not working, and it needs to be saved again to take effect.

Sorry, it's "Chrome".

**Comment by Juraj-Masiar** [comment]
Does reloading the page helps? Or only clicking the "Save" helps? (after you click Save, you should not need to reload the page)

I can't reproduce it here. Also I can't think of why would it not work when the value is stored. The config is loaded when the page loads so if it's there, it should work.
Maybe doing something wrong? I've set the config, restarted Chrome but it's still disabled on the page.

**Comment by xianghongai** [comment]
Configured to `mastergo.com/file*` works, configured to `mastergo.com/file/*` can reproduce. The problem is not big, I will close the Issue first, thank you for your efforts, the extension 很香 🍭
