### ISSUE TITLE
refund please 

### ISSUE THREAD

**Issue by Clintano** [fastaddons/ScrollAnywhere#68]
I didn't realize this was only safari, sorry. I thought I could use this across all my programs on my MacBook Pro. what do you need to process a refund?

**Comment by Juraj-Masiar** [comment]
I can't issue a refund, only App Store can. I'm not sure how though, but it's definitely possible.
I'm sorry I couldn't help more...

**Comment by Juraj-Masiar** [comment]
Here, this should help:
https://support.apple.com/en-us/HT204084
