### ISSUE TITLE
Compatibility with Thunderbird Conversations

### ISSUE THREAD

**Issue by Glandos** [fastaddons/ScrollAnywhere#75]
**Is your feature request related to a problem? Please describe.**
In Thunderbird, ScrollAnywhere works fine in the message view. But when using [Thunderbird Conversations](https://github.com/thunderbird-conversations/thunderbird-conversations/), the message view doesn't scroll any more.

**Describe the solution you'd like**
Make scrolling work within Conversations view.

**Describe alternatives you've considered**
Not using Conversations? Well, no.

**Additional context**
I'm using TB 128.

**Comment by Juraj-Masiar** [comment]
Sadly, this is not possible.
Addons are not allowed to run inside another addons (to keep them encapsulated to prevent collisions).

My addon is already telling Thunderbird (using special API) to "inject my scrolling script into every message/window", but when you use Thunderbird Conversations, it will open it's own "container" and show messages there, so Thunderbird won't inject there my script.
The Thunderbird Conversations addon would have to implement their own scrolling support.

**Comment by Glandos** [comment]
I think this can be closed then, thank you for your quick and detailed answer.
